on:
  push:
    tags:
      - dev.*
    branches:
      - dev
name: ssh
jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DEV_KNOWN_HOSTS }}
      - name: checkout
        uses: actions/checkout@v3
      - name: rsync over ssh
        run: rsync -ar --delete * ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:~/backend_temp
      - name: docker-compose
        run: ssh user@yourserver.example.com "cd /home/user/app/ && docker-compose up -d"

