on: [ push ]
name: ssh
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
