on: [ push, pull_request ]
name: ssh
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH Key
      - uses: shimataro/ssh-key-action@v2.3.1
